// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nplonbsyfkxcffwyaoze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbG9uYnN5Zmt4Y2Zmd3lhb3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDQ0NjksImV4cCI6MjA1OTIyMDQ2OX0.syOpHyzMKsMd2WOR1HWj17MTBZpeEcEHNE1ipLEN--0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);